namespace RenergeIA.Web.Services;

public sealed record PeligroBiblioteca(
    string Area,
    string Actividad,
    string Tarea,
    string Peligro,
    string Clasificacion,
    string EfectosPosibles,
    string ControlFuente,
    string ControlMedio,
    string ControlIndividuo,
    string MedidasIntervencion,
    string EPPRecomendado,
    string DocumentosAsociados,
    int NivelRiesgoSugerido   // NR típico GTC 45
);

public static class BibliotecaPeligrosData
{
    public static readonly IReadOnlyList<PeligroBiblioteca> Peligros =
    [
        // ══ OBRAS CIVILES — Excavaciones ══
        new("Obras Civiles", "Excavación", "Apertura de zanja",
            "Derrumbe o colapso de las paredes de la excavación",
            "Locativo",
            "Sepultamiento del trabajador, politraumatismos graves, muerte",
            "Entibado de paredes, taludes a 45°, distancia mínima de maquinaria a borde",
            "Señalización perimetral, barreras y cinta reflectiva",
            "Distancia mínima de 1,5 m del borde",
            "Inspección diaria antes del inicio, análisis de suelo, entibado certificado, permiso de excavación",
            "Casco, botas con puntera, chaleco reflectivo, guantes",
            "Permiso de excavación, ATS, procedimiento de trabajo seguro",
            4000),

        new("Obras Civiles", "Excavación", "Trabajos en zanja profunda (>1.5 m)",
            "Atmósfera deficiente en espacios confinados / acumulación de gases",
            "Químico",
            "Asfixia, intoxicación, muerte",
            "Ventilación forzada, detector de gases antes de ingresar",
            "Señalización de espacio confinado, vigía permanente",
            "Uso de arnés con línea de vida desde exterior",
            "Medición de gases O2/CO/H2S antes de ingresar, ATEX, rescate planificado",
            "Detector de gases portátil, arnés, línea de vida, casco",
            "Permiso de espacio confinado, ATS",
            6000),

        // ══ HINCADO DE POSTES / PILOTES ══
        new("Estructuras", "Hincado de perfiles", "Operación de hincadora",
            "Golpe por pieza metálica o cable de maniobra",
            "Mecánico",
            "Fracturas, contusiones severas, muerte por aplastamiento",
            "Procedimiento de maniobra con grúa, bloqueos y enclavamientos",
            "Zona de exclusión durante hincado, señalización de radio de seguridad",
            "Uso de cuerdas guía, personal fuera del radio de impacto",
            "Análisis de riesgo de maniobra, comunicación por radios, vigía de área",
            "Casco, botas puntera y suela antideslizante, chaleco, guantes anti-corte",
            "ATS, permiso de maniobra especial, plan de izaje si aplica",
            2400),

        // ══ MONTAJE DE ESTRUCTURA METÁLICA ══
        new("Estructuras", "Montaje de estructura", "Ensamble en campo",
            "Caída de piezas metálicas durante izado manual",
            "Mecánico",
            "Golpes, fracturas, amputaciones, muerte",
            "Uso de eslingas certificadas, precarga antes de izado",
            "Zona de exclusión bajo la carga, delimitación con cinta",
            "Chaleco reflectivo, casco, guantes anti-corte, botas puntera",
            "Plan de izaje, verificación de capacidad de equipos, comunicación radio",
            "Casco, guantes anti-corte, botas puntera, chaleco reflectivo",
            "Plan de izaje, ATS, permiso de maniobra",
            2400),

        new("Estructuras", "Montaje de estructura", "Trabajos en altura sobre estructura (>1.8 m)",
            "Caída a distinto nivel durante montaje de perfiles",
            "Locativo",
            "Politraumatismos, fractura de columna, muerte",
            "Plataformas de trabajo con barandas si es posible",
            "Líneas de vida horizontales en estructura, puntos de anclaje certificados",
            "Arnés de cuerpo completo, doble cola de vida, absorvedor de choque",
            "Permiso de trabajo en alturas, inspección de EPP, formación certificada",
            "Arnés clase III, doble cola de vida, casco con barbuquejo, botas antideslizantes",
            "Permiso de trabajo en alturas, ATS, plan de rescate en altura",
            4000),

        // ══ INSTALACIÓN DE MÓDULOS FOTOVOLTAICOS ══
        new("Módulos FV", "Instalación módulos", "Manipulación y transporte manual",
            "Sobre-esfuerzo y posturas forzadas por peso de módulos (aprox. 25 kg/unid.)",
            "Biomecánico",
            "Lumbalgia, hernias discales, lesiones musculo-esqueléticas",
            "Diseño de módulos livianos, carritos ergonómicos para transporte",
            "Procedimiento de dos personas para carga, ergonomía en sitio",
            "Uso de fajas lumbares cuando se requiera",
            "Capacitación en manejo manual de cargas, rotación de personal, pausas activas",
            "Faja lumbar (si procede), guantes, botas puntera, casco",
            "ATS, procedimiento de manejo manual de cargas",
            600),

        new("Módulos FV", "Instalación módulos", "Instalación en estructura a más de 1.8 m",
            "Caída a distinto nivel con módulo en mano",
            "Locativo",
            "Politraumatismos graves, fractura de extremidades, muerte",
            "Andamios o plataformas elevadoras certificadas cuando sea posible",
            "Líneas de vida, anclajes certificados en estructura",
            "Arnés cuerpo completo, doble cola de vida",
            "Permiso de trabajo en alturas, inspección de arneses, plan de rescate",
            "Arnés clase III, doble cola de vida, casco, botas antideslizantes",
            "Permiso de trabajo en alturas, ATS",
            4000),

        new("Módulos FV", "Instalación módulos", "Conexión de strings (CC)",
            "Contacto con tensión continua peligrosa (>50 V DC)",
            "Eléctrico",
            "Electrocución, quemaduras, paro cardíaco, muerte",
            "Diseño con seccionadores DC accesibles, cubiertas de protección en conectores",
            "Señalización de tensión peligrosa, barreras de acceso en cajas de strings",
            "Guantes dieléctricos clase 00 mínimo, gafas de arco",
            "Bloqueo/etiquetado (LOTO) antes de conexión, medición con multímetro CAT IV",
            "Guantes dieléctricos, gafas de arco, calzado dieléctrico, casco dieléctrico",
            "LOTO, ATS eléctrico, análisis de arco eléctrico",
            6000),

        // ══ INSTALACIONES ELÉCTRICAS AC ══
        new("Eléctricas AC", "Instalación eléctrica AC", "Tendido de conductores",
            "Contacto directo con conductores energizados (AC)",
            "Eléctrico",
            "Electrocución, quemaduras de arco, fibrilación ventricular, muerte",
            "Trabajo con líneas desenergizadas y LOTO, distancias de seguridad",
            "Señalización de peligro eléctrico, barreras físicas",
            "EPP dieléctrico clase adecuado al voltaje de trabajo",
            "Permiso de trabajo eléctrico, análisis de arco (NFPA 70E / NTC 2050), verificación ausencia tensión",
            "Guantes dieléctricos clase 2, casco clase E, gafas de arco, calzado dieléctrico",
            "Permiso trabajo eléctrico, LOTO, ATS eléctrico",
            6000),

        // ══ INVERSORES Y SALAS ELÉCTRICAS ══
        new("Salas Eléctricas", "Instalación de inversores", "Montaje y conexión de inversores",
            "Manejo de cargas pesadas (inversores >200 kg) con medios mecánicos",
            "Mecánico",
            "Aplastamiento, fracturas graves, muerte",
            "Uso de equipos de izaje certificados (montacargas, grúa pórtico)",
            "Zona de exclusión durante maniobra",
            "Uso de guías y cuerdas de control",
            "Plan de izaje, inspección de eslingas y grilletes, personal competente en maniobras",
            "Casco, chaleco, botas puntera, guantes de maniobra",
            "Plan de izaje, permiso de maniobra especial, ATS",
            2400),

        new("Salas Eléctricas", "Puesta en servicio (commissioning)", "Energización inicial del inversor",
            "Arco eléctrico durante energización de media tensión",
            "Eléctrico",
            "Quemaduras de arco grado III, ceguera, muerte",
            "Uso de protecciones de arco en paneles, distancias de seguridad",
            "Barreras de arco, personal mínimo durante energización",
            "EPP de arco eléctrico (cal/cm2 adecuado al nivel de incidente)",
            "Análisis flash hazard (NFPA 70E), procedimiento de energización paso a paso, coordinador eléctrico",
            "Traje de arco cal/cm2 calculado, casco dieléctrico, guantes dieléctricos clase 2, protector facial",
            "Permiso energización, análisis NFPA 70E, ATS eléctrico",
            6000),

        // ══ SUBESTACIÓN ELÉCTRICA ══
        new("Subestación", "Construcción subestación", "Armado de celdas MT y AT",
            "Exposición a tensiones de media/alta tensión",
            "Eléctrico",
            "Electrocución, quemaduras severas, muerte",
            "Diseño con distancias de seguridad normadas (RETIE), blindaje",
            "Señalización de zonas de alta tensión, barreras físicas permanentes",
            "EPP dieléctrico de alta tensión según nivel de tensión",
            "Trabajo bajo permiso eléctrico especial, distancias mínimas de aproximación, personal calificado",
            "Guantes AT, traje de arco, casco AT, pértiga de maniobra",
            "Permiso especial AT, análisis NFPA 70E, ATS",
            6000),

        // ══ IZAJES Y GRÚAS ══
        new("Izajes", "Maniobras de izaje", "Izado de estructuras o equipos pesados",
            "Caída de carga durante maniobra",
            "Mecánico",
            "Aplastamiento, muerte, daños a infraestructura",
            "Selección y verificación de equipos de izaje certificados, factor de seguridad 4 o mayor",
            "Zona de exclusión = 1,5 x altura de carga, delimitación perimetral",
            "Alejamiento de personal de zona de exclusión durante maniobra",
            "Plan de izaje firmado por rigger certificado, inspección pre-operacional, comunicación radio",
            "Casco, chaleco reflectivo, botas puntera, guantes",
            "Plan de izaje, permiso de maniobra, ATS de grúa",
            4000),

        // ══ TRABAJO EN ALTURAS ══
        new("General", "Trabajo en alturas", "Cualquier labor a más de 1.8 m",
            "Caída libre a distinto nivel",
            "Locativo",
            "Politraumatismos, fractura de columna vertebral, muerte",
            "Plataformas de trabajo con sistemas de protección colectiva",
            "Líneas de vida horizontales / verticales, anclajes certificados",
            "Arnés de cuerpo completo, doble cola de vida con absorvedor de choque",
            "Permiso de trabajo en alturas (Resolución 4272/2021), formación SENA/certificado, plan de rescate",
            "Arnés clase III, doble cola con absorvedor, casco con barbuquejo, botas antideslizantes",
            "Permiso trabajo en alturas (Res. 4272), ATS, plan de rescate",
            4000),

        // ══ ENERGIZACIÓN / COMMISSIONING ══
        new("Commissioning", "Pruebas y puesta en marcha", "Pruebas de aislamiento (Megger)",
            "Descarga capacitiva al retirar instrumento de medida",
            "Eléctrico",
            "Quemadura local, susto/caída por reacción, lesión en mano",
            "Uso de instrumentos con descarga automática integrada",
            "Procedimiento de descarga previa a retirar cables",
            "Guantes dieléctricos durante prueba",
            "Procedimiento de prueba paso a paso, verificar descarga completa antes de tocar",
            "Guantes dieléctricos, gafas de arco, calzado dieléctrico",
            "ATS eléctrico, permiso de trabajo",
            600),

        // ══ OPERACIÓN Y MANTENIMIENTO (O&M) ══
        new("O&M", "Mantenimiento preventivo", "Limpieza de módulos FV",
            "Golpe de calor y deshidratación en campo solar a alta temperatura",
            "Físico",
            "Golpe de calor, lipotimia, insolación, daño renal agudo",
            "Programación de labores en horas de menor radiación (antes de las 10h o después de las 15h)",
            "Zonas de sombra y hidratación en campo",
            "Ropa de trabajo clara, manga larga, protector solar FPS50+",
            "Plan de gestión de calor, hidratación frecuente (250 ml/15 min), monitoreo de temperatura",
            "Casco ventilado, ropa clara manga larga, botas, protector solar, agua",
            "ATS, plan de gestión de calor extremo",
            1200),

        new("O&M", "Mantenimiento preventivo", "Inspección visual y termografía",
            "Contacto con partes calientes (paneles a más de 70 grados en pleno sol)",
            "Físico",
            "Quemaduras de primer y segundo grado en manos",
            "Programación de termografía a primera hora de la mañana",
            "Señalización de superficies calientes",
            "Guantes resistentes al calor",
            "Termómetro infrarrojo para verificar temperatura antes de tocar, procedimiento de trabajo",
            "Guantes resistentes al calor, gafas de sol UV, casco",
            "ATS, instrucción de trabajo O&M",
            300),
    ];
}
